# Custom Language File for Launcher Customizer

[ejs.app]
title = "Helios Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "HERZLICH WILLKOMMEN!"
welcomeDescription = "Schön, dass du hier bist! Bereite dich auf ein spannendes Abenteuer vor und erkunde eine Welt voller Geheimnisse, Herausforderungen und Möglichkeiten. Egal, ob du allein oder mit Freunden spielst – hier beginnt dein persönliches Abenteuer."
welcomeDescCTA = "Mach dich bereit und starte dein Abenteuer jetzt!"
continueButton = "Weiter"